###############################################################################
# extractConfig.py  (v2.1 - hardened)
#
# WebSphere Configuration Drift Detection - Extraction Script
# Compatible with: WAS 8.5.5.x, Jython 2.1
#
# Hardening vs. previous version:
#   - Strips trailing whitespace/CR from all names returned by AdminConfig
#   - Validates each scope string is non-empty before passing to AdminTask
#   - Logs the exact configData string before each extract attempt
#   - Continues on per-scope failures (one bad app doesn't kill the whole run)
#   - Skips applications/scopes whose names contain characters known to break
#     extractConfigProperties (commas, equals, brackets, quotes)
#   - On failure, dumps full Java exception text including cause chain
###############################################################################

import sys
import os
import time
import re

def log(msg):
    ts = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    print "[%s] %s" % (ts, msg)


def ensureDir(path):
    if not os.path.exists(path):
        os.makedirs(path)


def removeTree(path):
    if not os.path.exists(path):
        return
    if os.path.isfile(path):
        os.remove(path)
        return
    for entry in os.listdir(path):
        full = os.path.join(path, entry)
        if os.path.isdir(full):
            removeTree(full)
        else:
            os.remove(full)
    os.rmdir(path)


def cleanName(raw):
    """
    Strip whitespace, CR, LF, and the (configId) suffix from a name returned
    by AdminConfig.list() / AdminConfig.getid().
    """
    if raw is None:
        return ''
    name = raw
    parenIdx = name.find('(')
    if parenIdx >= 0:
        name = name[:parenIdx]
    name = name.strip()
    return name


def isSafeName(name):
    """
    Return 1 if the name is safe to embed in a -configData scope string,
    0 otherwise. Names with these chars break the AdminTask argument parser.
    """
    if not name:
        return 0
    badChars = [',', '=', '[', ']', '"', "'", '\\', '\r', '\n', '\t']
    for c in badChars:
        if c in name:
            return 0
    return 1


def getCellName():
    out = AdminConfig.list('Cell')
    lines = out.splitlines()
    if not lines or not lines[0].strip():
        log("FATAL: AdminConfig.list('Cell') returned empty - not connected?")
        sys.exit(10)
    return cleanName(lines[0])


def getNodeNames():
    nodes = []
    out = AdminConfig.list('Node')
    for line in out.splitlines():
        name = cleanName(line)
        if name:
            nodes.append(name)
    return nodes


def getServerNames(cellName, nodeName):
    """Returns list of (serverName, serverType) tuples."""
    servers = []
    nodeScope = '/Cell:%s/Node:%s/' % (cellName, nodeName)
    try:
        out = AdminConfig.getid(nodeScope + 'Server:/')
    except Exception, e:
        log("  WARN: getid failed for %s: %s" % (nodeScope, str(e)))
        return servers
    for line in out.splitlines():
        line = line.strip()
        if not line:
            continue
        sname = cleanName(line)
        try:
            stype = AdminConfig.showAttribute(line, 'serverType')
            if stype is None:
                stype = 'UNKNOWN'
            stype = stype.strip()
        except Exception, e:
            log("  WARN: showAttribute(serverType) failed for %s: %s" %
                (sname, str(e)))
            stype = 'UNKNOWN'
        servers.append((sname, stype))
    return servers


def getClusterNames():
    clusters = []
    out = AdminConfig.list('ServerCluster')
    for line in out.splitlines():
        name = cleanName(line)
        if name:
            clusters.append(name)
    return clusters


def getAppNames():
    apps = []
    out = AdminApp.list()
    for line in out.splitlines():
        name = cleanName(line)
        if name:
            apps.append(name)
    return apps


VOLATILE_PATTERNS = [
    re.compile(r'^#ExtractedAt=.*$'),
    re.compile(r'^#.*Extracted on .*$'),
    re.compile(r'^#.*Generated by .*$'),
    re.compile(r'^.*_Websphere_Config_Data_Id=.*$'),
    re.compile(r'^.*_Websphere_Config_Data_Version=.*$'),
    re.compile(r'^#\s*SectionTopOrderID=.*$'),
]


def normalizeFile(path):
    if not os.path.exists(path):
        return
    f = open(path, 'rb')
    try:
        raw = f.read()
    finally:
        f.close()
    text = raw.replace('\r\n', '\n').replace('\r', '\n')
    lines = text.split('\n')
    cleaned = []
    for line in lines:
        skip = 0
        for pat in VOLATILE_PATTERNS:
            if pat.match(line):
                skip = 1
                break
        if skip:
            continue
        cleaned.append(line.rstrip())
    while len(cleaned) > 0 and cleaned[-1] == '':
        cleaned.pop()
    cleaned.append('')
    out = '\n'.join(cleaned)
    f = open(path, 'wb')
    try:
        f.write(out)
    finally:
        f.close()


def extractScope(outputFile, configData, label):
    """
    Run extractConfigProperties for one scope.
    Returns: 1 on success, 0 on failure.
    On failure, prints the configData (with repr) and full exception detail
    so you can diagnose 'Invalid Config Data' errors.
    """
    if not configData or configData.strip() == '':
        log("  SKIP %s: empty configData" % label)
        return 0

    log("Extracting %s -> %s" % (label, outputFile))
    log("  configData = %s" % repr(configData))

    try:
        AdminTask.extractConfigProperties([
            '-propertiesFileName', outputFile,
            '-configData', configData,
            '-options', '[[PortablePropertiesFile true]]'
        ])
        normalizeFile(outputFile)
        return 1
    except Exception, e:
        log("  ERROR extracting %s" % label)
        log("    Exception class: %s" % e.__class__.__name__)
        log("    Message: %s" % str(e))
        # Walk Java exception cause chain if present
        try:
            cause = e
            depth = 0
            while cause is not None and depth < 5:
                log("    [cause %d] %s: %s" %
                    (depth, cause.__class__.__name__, str(cause)))
                if hasattr(cause, 'getCause'):
                    nxt = cause.getCause()
                    if nxt is None or nxt == cause:
                        break
                    cause = nxt
                else:
                    break
                depth = depth + 1
        except:
            pass
        return 0


def extractAll(currentDir):
    ensureDir(currentDir)
    ensureDir(currentDir + '/nodes')
    ensureDir(currentDir + '/servers')
    ensureDir(currentDir + '/clusters')
    ensureDir(currentDir + '/applications')

    cellName = getCellName()
    log("Cell: %s" % repr(cellName))
    if not isSafeName(cellName):
        log("FATAL: cell name contains unsafe characters: %s" % repr(cellName))
        sys.exit(11)

    successCount = 0
    failCount = 0
    skipCount = 0

    # 1. Cell-level config
    if extractScope(currentDir + '/cell.props',
                    'Cell=' + cellName,
                    'Cell:' + cellName):
        successCount = successCount + 1
    else:
        failCount = failCount + 1

    # 2. Per-node config
    nodes = getNodeNames()
    log("Found %d nodes: %s" % (len(nodes), nodes))
    for node in nodes:
        if not isSafeName(node):
            log("  SKIP node with unsafe name: %s" % repr(node))
            skipCount = skipCount + 1
            continue
        configData = 'Cell=%s,Node=%s' % (cellName, node)
        outFile = '%s/nodes/%s.props' % (currentDir, node)
        if extractScope(outFile, configData, 'Node:' + node):
            successCount = successCount + 1
        else:
            failCount = failCount + 1

    # 3. Per-server config
    for node in nodes:
        if not isSafeName(node):
            continue
        servers = getServerNames(cellName, node)
        log("  Node %s has %d server(s): %s" %
            (node, len(servers), servers))
        for srv in servers:
            sname = srv[0]
            stype = srv[1]
            if stype == 'NODE_AGENT' or stype == 'DEPLOYMENT_MANAGER':
                log("  Skipping %s (%s)" % (sname, stype))
                continue
            if not isSafeName(sname):
                log("  SKIP server with unsafe name: %s" % repr(sname))
                skipCount = skipCount + 1
                continue
            configData = 'Cell=%s,Node=%s,Server=%s' % \
                         (cellName, node, sname)
            outFile = '%s/servers/%s__%s.props' % (currentDir, node, sname)
            if extractScope(outFile, configData, 'Server:' + sname):
                successCount = successCount + 1
            else:
                failCount = failCount + 1

    # 4. Per-cluster config
    clusters = getClusterNames()
    log("Found %d clusters: %s" % (len(clusters), clusters))
    for cluster in clusters:
        if not isSafeName(cluster):
            log("  SKIP cluster with unsafe name: %s" % repr(cluster))
            skipCount = skipCount + 1
            continue
        configData = 'Cell=%s,ServerCluster=%s' % (cellName, cluster)
        outFile = '%s/clusters/%s.props' % (currentDir, cluster)
        if extractScope(outFile, configData, 'Cluster:' + cluster):
            successCount = successCount + 1
        else:
            failCount = failCount + 1

    # 5. Per-application config
    apps = getAppNames()
    log("Found %d applications: %s" % (len(apps), apps))
    for app in apps:
        if not isSafeName(app):
            log("  SKIP app with unsafe name (spaces/special chars): %s" %
                repr(app))
            skipCount = skipCount + 1
            continue
        configData = 'Cell=%s,Deployment=%s' % (cellName, app)
        outFile = '%s/applications/%s.props' % (currentDir, app)
        if extractScope(outFile, configData, 'App:' + app):
            successCount = successCount + 1
        else:
            failCount = failCount + 1

    log("=====================================")
    log("Extraction complete. Success: %d, Failed: %d, Skipped: %d" %
        (successCount, failCount, skipCount))
    log("=====================================")
    return failCount


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
if len(sys.argv) < 1:
    print "Usage: wsadmin.sh -lang jython -f extractConfig.py <snapshots_root>"
    sys.exit(1)

snapshotsRoot = sys.argv[0]
currentDir = snapshotsRoot + '/current'

log("Starting WebSphere config extraction (v2.1 hardened)")
log("Snapshots root: %s" % snapshotsRoot)
log("Writing to:     %s" % currentDir)

if os.path.exists(currentDir):
    log("Removing stale %s" % currentDir)
    removeTree(currentDir)

ensureDir(snapshotsRoot)
failures = extractAll(currentDir)

# Exit 0 even on partial failures so drift_engine still processes whatever
# was extracted successfully. Total failure (empty current/) is detected
# downstream by drift_engine.
log("Done. Per-scope failures: %d (orchestrator continues regardless)" %
    failures)
sys.exit(0)
